service: rimac-appointment-backend
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-offline

custom: ${file(./infrastructure/custom.yml)}

provider:
  name: aws
  runtime: nodejs18.x
  region: ${self:custom.region}
  stage: ${self:custom.stage}
  memorySize: 1024
  timeout: 29
  environment: ${file(./infrastructure/environments/${self:custom.stage}.yml)}
  iam:
    role: !GetAtt LambdaExecutionRole.Arn

functions: ${file(./infrastructure/functions.yml)}

resources:
  - ${file(./infrastructure/resources/iam-roles.yml)}
  - ${file(./infrastructure/resources/dynamodb.yml)}
  - ${file(./infrastructure/resources/sns-sqs.yml)}
  - ${file(./infrastructure/resources/eventbridge.yml)}
  - ${file(./infrastructure/resources/iam-roles.yml)}
  # - ${file(./infrastructure/resources/ses.yml)}
  - ${file(./infrastructure/outputs.yml)}
